### ISSUE TITLE
Load phase generated invalid SQL

### ISSUE THREAD

**Issue by carpii** [facebook/linkbench#32]
I've populated linkdb from scratch several times over the past week, but today I opted for a lower maxid. 
Right at the end of the loading phase, the tool seems to have generated invalid an sql command...

Using latest repo (108b1db77412f5c7) and Percona Server 5.6.24-72.2
MyConfig.properties are left at defaults, apart from auth credentials

> ./bin/linkbench -D maxid1=32000001 -c config/MyConfig.properties -l

````
INFO 2015-07-01 07:28:42,059 [Thread-8]: ThreadID = 8 LOAD_LINKS_BULK_NLINKS totalOps = 13839 totalErrors = 0 ops = 13839 sampleDuration = 987121ms samples = 10000 mean = 1023.94 min = 453 25% = 1024 50% = 1024 75% = 1024 90% = 1024 95% = 1024 99% = 1024 max = 1024
INFO 2015-07-01 07:28:42,059 [Thread-8]: ThreadID = 8 LOAD_COUNTS_BULK_NLINKS totalOps = 2334 totalErrors = 0 ops = 2334 sampleDuration = 987121ms samples = 2334 mean = 1023.68 min = 285 25% = 1024 50% = 1024 75% = 1024 90% = 1024 95% = 1024 99% = 1024 max = 1024

ERROR 2015-07-01 07:32:30,941 [Thread-10]: SQLException thrown by MySQL driver during execution of operation: bulkAddNodes.  Message was: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '; commit' at line 1'.  SQLState was: 42000.  Error is probably non-transient, will abort operation.

ERROR 2015-07-01 07:32:30,941 [Thread-10]: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '; commit' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '; commit' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2728)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1811)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1899)
	at com.facebook.LinkBench.LinkStoreMysql.bulkAddNodesImpl(LinkStoreMysql.java:957)
	at com.facebook.LinkBench.LinkStoreMysql.bulkAddNodes(LinkStoreMysql.java:928)
	at com.facebook.LinkBench.NodeLoader.loadNodes(NodeLoader.java:184)
	at com.facebook.LinkBench.NodeLoader.run(NodeLoader.java:147)
	at com.facebook.LinkBench.LinkBenchDriver$1.run(LinkBenchDriver.java:439)
	at java.lang.Thread.run(Thread.java:745)

INFO 2015-07-01 07:32:30,943 [Thread-10]: Reopening MySQL connection in threadID 10
INFO 2015-07-01 07:32:32,111 [Thread-10]: Loading of nodes [1,32000001) done
INFO 2015-07-01 07:32:32,112 [Thread-10]: ThreadID = 10 LOAD_NODE_BULK totalOps = 31251 totalErrors = 1 ops = 31251 sampleDuration = 1217373ms samples = 10000 mean = 35944.31 min = 13603 25% = 16853 50% = 23338 75% = 36969 90% = 70419 95% = 101225 99% = 187492 max = 1579119
INFO 2015-07-01 07:32:32,114 [main]: LOAD_NODE_BULK count = 31250  p25 = [16,17]ms  p50 = [23,24]ms  p75 = [37,38]ms  p95 = [99,100]ms  p99 = [100,200]ms  max = 3140.668ms  mean = 36.277ms
INFO 2015-07-01 07:32:32,114 [main]: LOAD_LINKS_BULK count = 137202  p25 = [30,31]ms  p50 = [40,41]ms  p75 = [69,70]ms  p95 = [100,200]ms  p99 = [200,300]ms  max = 4699.146ms  mean = 63.275ms
INFO 2015-07-01 07:32:32,114 [main]: LOAD_COUNTS_BULK count = 24132  p25 = [15,16]ms  p50 = [20,21]ms  p75 = [38,39]ms  p95 = [98,99]ms  p99 = [100,200]ms  max = 1564.99ms  mean = 34.802ms
INFO 2015-07-01 07:32:32,115 [main]: LOAD PHASE COMPLETED.  Loaded 32000000 nodes (Expected 32000000). Loaded 140489958 links (4.39 links per node).  Took 1218.4 seconds.  Links/second = 115302
INFO 2015-07-01 07:32:32,115 [main]: Skipping request phase per the cmdline arg
````

**Comment by mdcallag** [comment]
Can you share your config/LinkConfigMysql.properties file? I might have seen this error a long time ago. I don't remember seeing it recently and I run linkbench a lot.

Does it reproduce for you?

**Comment by carpii** [comment]
> Can you share your config/LinkConfigMysql.properties file?

That config is identical to the one in github at the moment
````
~/linkbench/config> md5sum LinkConfigMysql.properties
0a5fc7a4e6575fd4a70ea433fb143984  LinkConfigMysql.properties
````

I do explicitly pass a MyConfig.properties, although this is just a copy of the above, with the db login and password updated..

````
~/linkbench/config> diff LinkConfigMysql.properties MyConfig.properties
30,32c30,32
< host = yourhostname.here
< user = MySQLuser
< password = MySQLpass
---
> host = localhost
> user = linkbench
> password = XXXXXXX
````

I have not tried reproducing yet, as it was not critical for me, I just thought it curious having ran it so many times and not seen the error before. 

I will try to reproduce in the next few days

**Comment by maykov** [comment]
Which MySQL fork and version do you use? It doesn't repro on 5.6 Webscale SQL.

**Comment by carpii** [comment]
@maykov it was against Percona Server 5.6 (from their official rpms).

Like I say though, Id been using linkbench for a good while before I suddenly got that error, so its some obscure circumstances which result in invalid SQL I guess

**Comment by mdcallag** [comment]
closing given the lack of feedback. I use linkbench frequently. I might have seen this error once but didn't try to debug it. It doesn't prevent me from getting things done.

**Comment by carpii** [comment]
> It doesn't prevent me from getting things done.

No probs. Like i say it was intermittent for me too.

Just thought Id report it incase QA was important with linkbench :-)
