### ISSUE TITLE
LinkBench Does Not Work on MemoryLinkStore

### ISSUE THREAD

**Issue by ellitron** [facebook/linkbench#33]
Normally the load and request phases of LinkBench can be run separately, because the LinkStore is a remote database that maintains its state after the load phase completes, so that the request phase performs requests on the loaded database. But the MemoryLinkStore's data lives locally in the LinkBench process itself, meaning that the load and request phase must be performed one after the other in the same LinkBench process. However, the load phase of LinkBench does not pass a reference to the loaded MemoryLinkStore to the request phase. See `LinkBenchDriver.java`:
```c++
  void drive() throws IOException, InterruptedException, Throwable {
    load();
    sendrequests();
  }
```
The `sendRequests()` method executes without any reference to the loaded MemoryLinkStore. `sendRequests()` actually creates a new store using the `initStores()` method:

```c++
  // generate instances of LinkStore and NodeStore
  private Stores initStores()
    throws Exception {
    LinkStore linkStore = createLinkStore();
    NodeStore nodeStore = createNodeStore(linkStore);

    return new Stores(linkStore, nodeStore);
  }
```

Which in turn calls `createLinkStore()`, which simply looks up which class to use for creating the new store, and then calls the empty constructor for that object.

Therefore, when running the request phase, LinkBench reports the following error, even though the load phase has already been executed:

```
ERROR 2015-09-01 10:03:30,530 [Thread-2]: ADD_NODE error dbid linkdb was not initialized
java.lang.Exception: dbid linkdb was not initialized
	at com.facebook.LinkBench.MemoryLinkStore.getNodeDB(MemoryLinkStore.java:396)
	at com.facebook.LinkBench.MemoryLinkStore.addNode(MemoryLinkStore.java:417)
	at com.facebook.LinkBench.LinkBenchRequest.oneRequest(LinkBenchRequest.java:607)
	at com.facebook.LinkBench.LinkBenchRequest.run(LinkBenchRequest.java:778)
	at com.facebook.LinkBench.LinkBenchDriver$1.run(LinkBenchDriver.java:439)
	at java.lang.Thread.run(Thread.java:722)
```

For the dummy MemoryLinkStore to not work is a little odd to me, making me think that I've missed something here. If I have, please let me know. Otherwise, some way is needed to pass on the loaded MemoryLinkStore database to the request phase.

**Comment by maykov** [comment]
I have never used it, so I don't know. I only benchmarked MySQL and RocksDB. Do you have any particular reasons for benchmarking memory store?

**Comment by timarmstrong** [comment]
MemoryLinkStore was intended for unit tests and as a simple reference example for the interface - you running a full benchmark on it in that way isn't supported.

**Comment by ellitron** [comment]
My reason for benchmarking the memory store is to find an upper bound for performance (or lower bound if we're talking about latency). I'm testing LinkBench against RAMCloud, an in-memory key value store, and measuring latency. I would like to see what the latency numbers would be for an embedded database, which would give a nice lower bound for any in-memory database.

**Comment by maykov** [comment]
Feel free to fix it and send a pull request.

**Comment by timarmstrong** [comment]
You could probably make it work with a combined load and request phase. I think it would be interesting experiment, but keep in mind that it wasn't really written with performance in mind. It's pretty simple, but there are two big locks used to protect the node and links stores.

**Comment by ellitron** [comment]
Hmm I see... So far I've hacked the load phase to hand off a loaded store to the request phase, and running only a single requester against it. Thanks for pointing out the locking issue.

Has anyone published performance numbers of LinkBench against various databases? I do see some here and there, like one published recently on Small Datum's blog, but like the rest it leaves quite a lot to be desired in terms of details, and doesn't include popular graph databases like Neo4j or TitanDB. I just want to make sure I'm not overlooking something here.

**Comment by mdcallag** [comment]
I consider myself lucky if an academic paper tells me which version of
MySQL they used. I usually don't see more than that.

I sometimes include my.cnf settings in my posts at smalldatum, along with
changes to Linkbench settings and some details on the HW, OS and filesystem
used. Full reproduction requires more if you want to compare your results
with my results. Because there are so many details, I prefer to do
comparisons only with other results I generate. You don't have access to
some of the HW that I use. I doubt that you use all of the Linux patches
that I have. I'd rather not worry if my results suffer because I used
different settings in /proc/sys than someone else.

Linkbench results have only been published for MongoDB and MySQL. Most of
the MongoDB results cheat by not using transactions for assoc_add and
assoc_delete. AFAIK Linkbench has only been implemented for MySQL and
MongoDB. I don't expect it to be great on a graph db because Linkbench is
much more about transaction processing than it is about graph processing. I
am interested in an port and results for Postgres but that has yet to
happen.

**Comment by ellitron** [comment]
Hi Mark, thanks for that response. That makes sense. Looking at those numbers that you published, though, it seems like you must be using one beefy machine. Running MySQL 5.6.26 stock with the buffer cache set to contain a 10M node graph (roughly 12GB on disk) on our servers gets about 200 ops per second for a single requester thread hitting the server. Seeing you numbers for 20 threads for the unpartitioned, uncompressed benchmark leaves me wondering if the difference between our numbers is really all in the hardware and the facebook patch (perhaps there's some voodoo MySQL tuning that I'm overlooking). Our servers are a bit old, but ought to get the job done storing the entire dataset in memory: (Xeon X3470 (4x2.93 GHz cores, 3.6 GHz Turbo), 24 GB DDR3 at 800 MHz, Crucial M4 SSD (CT128M4SSD2 (128 GB)), and Mellanox ConnectX-2 Infiniband HCA NICs). 

It would also be really interesting to see not just was 20 requesters can get in terms of throughput, but how that varies as you vary the total requesters. Do 20 requesters max out your MySQL server, or can it go even further? Does more offered load cause the server to take a nose dive or does it plateau graciously? How does latency fair at low and high load? What about 99.9 and 99.99th percentile latencies? How often do spikes occur, and by how much? I'm just rattling off things that I would find particularly interesting to see in your study. 

Given that it took you 12 hours to get a single data-point, I can imagine running a parameter sweep could potentially be a nightmare. Did you find that a 12h run was necessary for the throughput to stabilize? Do you know at what point the throughput stabilized, and why it takes that long to stabilize?

I noticed, oddly, that in our own performance tests of MySQL on InnoDB that the performance would go up by 15% or so for a good hour, and then down 15% for the next hour, oscillating forever in roughly hour intervals. I have yet to figure out if there's something strange going on in our cluster, or if it's something in MySQL...

**Comment by mdcallag** [comment]
There are nice features in YCSB to find the saturation point where response
time grows too much. I wish we had something like that in linkbench but it
has yet to be added.

I would start by looking at single-thread response time. I will share more
details with you tomorrow. I have two NUC servers at home (4 HW threads,
core i3 or i5?, 1 disk, 1 cheap SSD, 8G RAM) but I have not shared many
numbers from them.

Configuration can be a pain and trying to understand the impact of each
option isn't possible in finite time. While I set many options, there are
probably only 10 that really matter.

InnoDB performance can vary from stalls when fuzzy checkpoint doesn't keep
up or gets in the way. This has gotten much better over time. I can also
reproduce similar effects in WiredTiger, mmapv1, RocksDB and ForestDB so I
don't feel too bad about InnoDB. But we continue to push on the vendor to
make it better. Proper IO tuning for InnoDB can also help a lot (will share
details tomorrow).

I use N 1-hour intervals to look for performance getting bad over time. I
am not sure when I started doing that but it has been useful to find
problems in WiredTiger and RocksDB. The database grows over time because
rows are added so I expect some drop in performance.

I use 20 request threads because my server has 40 HW threads with HT
enabled, so my client count is #(HW threads) / 2. I haven't shown this is a
great number. For most of my tests I put linkbench and mysqld on the same
host to avoid variance from the production network. In production we don't
co-locate clients and mysqld.

For now can you share:
* last 50 lines of linkbench output
* your my.cnf
* output from "SHOW GLOBAL VARIABLES" run against mysqld

On Tue, Sep 1, 2015 at 5:19 PM, Jonathan Ellithorpe <
notifications@github.com> wrote:

> Hi Mark, thanks for that response. That makes sense. Looking at those
> numbers that you published, though, it seems like you must be using one
> beefy machine. Running MySQL 5.6.26 stock with the buffer cache set to
> contain a 10M node graph (roughly 12GB on disk) on our servers gets about
> 200 ops per second for a single requester thread hitting the server. Seeing
> you numbers for 20 threads for the unpartitioned, uncompressed benchmark
> leaves me wondering if the difference between our numbers is really all in
> the hardware and the facebook patch (perhaps there's some voodoo MySQL
> tuning that I'm overlooking). Our servers are a bit old, but ought to get
> the job done storing the entire dataset in memory: (Xeon X3470 (4x2.93 GHz
> cores, 3.6 GHz Turbo), 24 GB DDR3 at 800 MHz, Crucial M4 SSD (CT128M4SSD2
> (128 GB)), and Mellanox ConnectX-2 Infiniband HCA NICs).
>
> It would also be really interesting to see not just was 20 requesters can
> get in terms of throughput, but how that varies as you vary the total
> requesters. Do 20 requesters max out your MySQL server, or can it go even
> further? Does more offered load cause the server to take a nose dive or
> does it plateau graciously? How does latency fair at low and high load?
> What about 99.9 and 99.99th percentile latencies? How often do spikes
> occur, and by how much? I'm just rattling off things that I would find
> particularly interesting to see in your study.
>
> Given that it took you 12 hours to get a single data-point, I can imagine
> running a parameter sweep could potentially be a nightmare. Did you find
> that a 12h run was necessary for the throughput to stabilize? Do you know
> at what point the throughput stabilized, and why it takes that long to
> stabilize?
>
> I noticed, oddly, that in our own performance tests of MySQL on InnoDB
> that the performance would go up by 15% or so for a good hour, and then
> down 15% for the next hour, oscillating forever in roughly hour intervals.
> I have yet to figure out if there's something strange going on in our
> cluster, or if it's something in MySQL...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/linkbench/issues/33#issuecomment-136899436>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by ellitron** [comment]
Sure thing! 

* last 50 lines of linkbench output for 1 requester against a MySQL database loaded with 10M node graph with the facebook link distribution:

https://dl.dropboxusercontent.com/u/13067583/requester.log

* my.cnf

https://dl.dropboxusercontent.com/u/13067583/my.cnf

* output from "SHOW GLOBAL VARIABLES"

https://dl.dropboxusercontent.com/u/13067583/mysql_globals.txt

**Comment by mdcallag** [comment]
Throughput isn't great because of fsync latency. If you look at p50 for all
of the ADD_*, UPDATE_* and DELETE_* operations at the end of the linkbench
output, they are ~10 milliseconds. I assume you don't have HW RAID and
mysqld can't do much about slow fsync.

A workaround is to disable fsync on commit. There is an fsync for the
InnoDB redo log because innodb_flush_log_at_trx_commit is set to 1 by
default. Add this to my.cnf to have a background thread do ~1 fsync per
second for the redo log and the threads running user transactions will skip
the fsync:
   innodb_flush_log_at_trx_commit=2

http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit

On Tue, Sep 1, 2015 at 6:04 PM, Jonathan Ellithorpe <
notifications@github.com> wrote:

> Sure thing!
>
>    - last 50 lines of linkbench output for 1 requester against a MySQL
>    database loaded with 10M node graph with the facebook link distribution:
>
> https://dl.dropboxusercontent.com/u/13067583/requester.log
>
>    - my.cnf
>
> https://dl.dropboxusercontent.com/u/13067583/my.cnf
>
>    - output from "SHOW GLOBAL VARIABLES"
>
> https://dl.dropboxusercontent.com/u/13067583/mysql_globals.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/linkbench/issues/33#issuecomment-136906874>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by ellitron** [comment]
Well that certainly helped. Setting innodb_flush_log_at_trx_commit=2 boosted me from 200 ops/s to 900 ops/s. I went a step further and set the flush timeout to 2000 seconds, effectively eliminating fsyncs entirely while I run a 600 second workload, and get about 1200 ops / s. That gets me closer to what seems like about 2kops/s per thread that you're getting, maybe the rest of this difference is really in the CPU and memory subsystem.

For reference, here are some quick benchmarks of my SSDs:

```
>$ dd if=/dev/zero of=/tmp/writetest bs=8k count=131072; rm /tmp/writetest
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB) copied, 0.614622 s, 1.7 GB/s
>$ dd if=/dev/zero of=/tmp/writetest bs=8k count=131072 conv=fdatasync; rm /tmp/writetest
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB) copied, 6.6794 s, 161 MB/s
>$ dd if=/dev/zero of=/tmp/writetest bs=8k count=131072 oflag=sync; rm /tmp/writetest
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB) copied, 1371.54 s, 783 kB/s
```
